version: '3.8'

services:
  streamlit:
    build: .
    container_name: portafolio-davidcarusso
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_SERVER_ADDRESS=davidcarusso.com.ar
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s