[browser]
serverAddress = "davidcarusso.com.ar"
gatherUsageStats = false

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
headless = true

[theme]
base="dark"
primaryColor = "#667eea"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"


[client]
showErrorDetails = false
toolbarMode = "minimal"